In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('emnist-byclass-train.csv')

In [3]:
train_data.head()

,35,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.466,0.467,0.468,0.469,0.470,0.471,0.472,0.473,0.474,0.475
0,36,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
dic = train_data['35'].value_counts()

In [8]:
dat = pd.DataFrame()
for i in range(62):
    aux = train_data[train_data['35']==i]
    if len(aux)>5000:
        aux = aux[0:5001]
    dat = pd.concat([dat, aux], ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'value_counts'

In [9]:
dat['35'].value_counts()

30    5001
37    5001
29    5001
28    5001
27    5001
25    5001
24    5001
23    5001
22    5001
21    5001
18    5001
15    5001
12    5001
10    5001
9     5001
8     5001
7     5001
6     5001
5     5001
4     5001
3     5001
2     5001
1     5001
36    5001
0     5001
47    5001
55    5001
49    5001
43    5001
40    5001
      ...
14    4934
34    4743
32    4695
31    4637
13    4562
11    3878
19    3762
42    3687
17    3152
52    2994
57    2910
38    2854
56    2830
59    2822
33    2771
50    2749
61    2725
44    2725
35    2700
54    2699
58    2697
48    2645
26    2605
41    2561
16    2517
46    2491
20    2468
51    2448
60    2365
45    1896
Name: 35, Length: 62, dtype: int64

In [11]:
dat.info

<bound method DataFrame.info of         35  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.466  0.467  \
0        0  0    0    0    0    0    0    0    0    0  ...      0      0
1        0  0    0    0    0    0    0    0    0    0  ...      0      0
2        0  0    0    0    0    0    0    0    0    0  ...      0      0
3        0  0    0    0    0    0    0    0    0    0  ...      0      0
4        0  0    0    0    0    0    0    0    0    0  ...      0      0
5        0  0    0    0    0    0    0    0    0    0  ...      0      0
6        0  0    0    0    0    0    0    0    0    0  ...      0      0
7        0  0    0    0    0    0    0    0    0    0  ...      0      0
8        0  0    0    0    0    0    0    0    0    0  ...      0      0
9        0  0    0    0    0    0    0    0    0    0  ...      0      0
10       0  0    0    0    0    0    0    0    0    0  ...      0      0
11       0  0    0    0    0    0    0    0    0    0  ...      0      0
12       0  0    0    0    0    0    0    0    0    0  ...      0      0
13       0  0    0    0    0    0    0    0    0    0  ...      0      0
14       0  0    0    0    0    0    0    0    0    0  ...      0      0
15       0  0    0    0    0    0    0    0    0    0  ...      0      0
16       0  0    0    0    0    0    0    0    0    0  ...      0      0
17       0  0    0    0    0    0    0    0    0    0  ...      0      0
18       0  0    0    0    0    0    0    0    0    0  ...      0      0
19       0  0    0    0    0    0    0    0    0    0  ...      0      0
20       0  0    0    0    0    0    0    0    0    0  ...      0      0
21       0  0    0    0    0    0    0    0    0    0  ...      0      0
22       0  0    0    0    0    0    0    0    0    0  ...      0      0
23       0  0    0    0    0    0    0    0    0    0  ...      0      0
24       0  0    0    0    0    0    0    0    0    0  ...      0      0
25       0  0    0    0    0    0    0    0    0    0  ...      0      0
26       0  0    0    0    0    0    0    0    0    0  ...      0      0
27       0  0    0    0    0    0    0    0    0    0  ...      0      0
28       0  0    0    0    0    0    0    0    0    0  ...      0      0
29       0  0    0    0    0    0    0    0    0    0  ...      0      0
...     .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...
253524  61  0    0    0    0    0    0    0    0    0  ...      0      0
253525  61  0    0    0    0    0    0    0    0    0  ...      0      0
253526  61  0    0    0    0    0    0    0    0    0  ...      0      0
253527  61  0    0    0    0    0    0    0    0    0  ...      0      0
253528  61  0    0    0    0    0    0    0    0    0  ...      0      0
253529  61  0    0    0    0    0    0    0    0    0  ...      0      0
253530  61  0    0    0    0    0    0    0    0    0  ...      0      0
253531  61  0    0    0    0    0    0    0    0    0  ...      0      0
253532  61  0    0    0    0    0    0    0    0    0  ...      0      0
253533  61  0    0    0    0    0    0    0    0    0  ...      0      0
253534  61  0    0    0    0    0    0    0    0    0  ...      0      0
253535  61  0    0    0    0    0    0    0    0    0  ...      0      0
253536  61  0    0    0    0    0    0    0    0    0  ...      0      0
253537  61  0    0    0    0    0    0    0    0    0  ...      0      0
253538  61  0    0    0    0    0    0    0    0    0  ...      0      0
253539  61  0    0    0    0    0    0    0    0    0  ...      0      0
253540  61  0    0    0    0    0    0    0    0    0  ...      0      0
253541  61  0    0    0    0    0    0    0    0    0  ...      0      0
253542  61  0    0    0    0    0    0    0    0    0  ...      0      0
253543  61  0    0    0    0    0    0    0    0    0  ...      0      0
253544  61  0    0    0    0    0    0    0    0    0  ...      0      0
253545  61  0    0    0    0    0    0    0    0    0  ...      0      0
253546  61  0    0    0    0    0    0    0    0    0  ...      0      0
253547  61  0    0    0    0    0    0    0    0    0  ...      0      0
253548  61  0    0    0    0    0    0    0    0    0  ...      0      0
253549  61  0    0    0    0    0    0    0    0    0  ...      0      0
253550  61  0    0    0    0    0    0    0    0    0  ...      0      0
253551  61  0    0    0    0    0    0    0    0    0  ...      0      0
253552  61  0    0    0    0    0    0    0    0    0  ...      0      0
253553  61  0    0    0    0    0    0    0    0    0  ...      0      0

        0.468  0.469  0.470  0.471  0.472  0.473  0.474  0.475
0           0      0      0      0      0      0      0      0
1           0      0      0      0      0      0      0      0
2           0      0      0      0      0      0      0      0
3           0      0      0      0      0      0      0      0
4           0      0      0      0      0      0      0      0
5           0      0      0      0      0      0      0      0
6           0      0      0      0      0      0      0      0
7           0      0      0      0      0      0      0      0
8           0      0      0      0      0      0      0      0
9           0      0      0      0      0      0      0      0
10          0      0      0      0      0      0      0      0
11          0      0      0      0      0      0      0      0
12          0      0      0      0      0      0      0      0
13          0      0      0      0      0      0      0      0
14          0      0      0      0      0      0      0      0
15          0      0      0      0      0      0      0      0
16          0      0      0      0      0      0      0      0
17          0      0      0      0      0      0      0      0
18          0      0      0      0      0      0      0      0
19          0      0      0      0      0      0      0      0
20          0      0      0      0      0      0      0      0
21          0      0      0      0      0      0      0      0
22          0      0      0      0      0      0      0      0
23          0      0      0      0      0      0      0      0
24          0      0      0      0      0      0      0      0
25          0      0      0      0      0      0      0      0
26          0      0      0      0      0      0      0      0
27          0      0      0      0      0      0      0      0
28          0      0      0      0      0      0      0      0
29          0      0      0      0      0      0      0      0
...       ...    ...    ...    ...    ...    ...    ...    ...
253524      0      0      0      0      0      0      0      0
253525      0      0      0      0      0      0      0      0
253526      0      0      0      0      0      0      0      0
253527      0      0      0      0      0      0      0      0
253528      0      0      0      0      0      0      0      0
253529      0      0      0      0      0      0      0      0
253530      0      0      0      0      0      0      0      0
253531      0      0      0      0      0      0      0      0
253532      0      0      0      0      0      0      0      0
253533      0      0      0      0      0      0      0      0
253534      0      0      0      0      0      0      0      0
253535      0      0      0      0      0      0      0      0
253536      0      0      0      0      0      0      0      0
253537      0      0      0      0      0      0      0      0
253538      0      0      0      0      0      0      0      0
253539      0      0      0      0      0      0      0      0
253540      0      0      0      0      0      0      0      0
253541      0      0      0      0      0      0      0      0
253542      0      0      0      0      0      0      0      0
253543      0      0      0      0      0      0      0      0
253544      0      0      0      0      0      0      0      0
253545      0      0      0      0      0      0      0      0
253546      0      0      0      0      0      0      0      0
253547      0      0      0      0      0      0      0      0
253548      0      0      0      0      0      0      0      0
253549      0      0      0      0      0      0      0      0
253550      0      0      0      0      0      0      0      0
253551      0      0      0      0      0      0      0      0
253552      0      0      0      0      0      0      0      0
253553      0      0      0      0      0      0      0      0

[253554 rows x 785 columns]>

In [12]:
dat.to_csv('new_emnist_train.csv')